"""create_table_expense

Revision ID: 3de942fd45e9
Revises: 
Create Date: 2020-07-25 07:46:28.103400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de942fd45e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(64), nullable=False, unique=True),
                    sa.Column('color', sa.String(64), nullable=True, unique=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('types_idx', 'types', ['id'])
    op.create_table('expenses',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(64), nullable=False),
        sa.Column('amount', sa.Float, nullable=False),
        sa.Column('date', sa.DateTime, nullable=True),
        sa.Column('place', sa.String(124), nullable=True),
        sa.Column('month', sa.Enum('January','February','March','April','Maio','June','July','August','September','October','November','December', name='month'), nullable=False),
        sa.Column('type_id', sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    # ### end Alembic commands ###
