# DATABASE_URL = 'postgresql://user:password@localhost:5432/postgres'
# DATABASE_URL = 'postgresql+pg8000://user:password@localhost/postgres'
# f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
# DATABASE_URL = 'postgres+psycopg2://user:password@localhost:5432/postgres'
DATABASE_URL= 'postgres+psycopg2://user:password@localhost:5432/postgres'
